FROM php:7.2-apache

WORKDIR /app

# COPY . ../public

# WORKDIR /usr/src/myapp

# CMD [ "php", "./your-script.php" ]

# COPY ./wait-for-it.sh /wait-for-it.sh
# COPY ./php_start_command.sh /php_start_command.sh

# COPY ./php_check_is_migrated.php /php_check_is_migrated.php

# CMD ["/php_start_command.sh"]
