<article>
  <h1>Ziele der Bits & Bäume Konferenz</h1>
  <p>Wir bringen Communities zusammen!</p>
  <p>In den letzten Jahrzehnten sind gesellschaftsverändernde Bewegungen gewachsen, die jeweils ihren eigenen Utopien folgen: Sie kämpfen dafür, die Natur und unsere natürlichen Lebensgrundlagen zu erhalten, für weltweit faire Arbeitsbedingungen ohne Ausbeutung, für eine Eindämmung der Macht von Konzernen und gegen die Zerstörung des Planeten. Sie setzen sich ein für demokratische Teilhabe, für nachhaltige Produktions- und Konsumweisen, für gerechten Handel zwischen globalem Süden und Norden und für verbindliche Regeln für die Wirtschaft im Sinne dieser Ziele. Andere Communities arbeiten daran, die Digitalisierung so zu gestalten, dass Bürgerrechte, Schutz der Privatsphäre, Datenschutz, Souveränität und Demokratie für eine offene Gesellschaft gewahrt sind. Sie stehen auf für einen freien Zugang zum Wissen der Mächtigen und der Konzerne, für eine Kultur des Miteinander-Teilens, für eine überwachungsfreie digitale Welt, für flache Hierarchien, globale Vernetzung und Dezentralität, für Selbstbestimmung und Menschenrechte angesichts eines Zeitalters der Künstlichen Intelligenz und der Übermacht globaler Internet-Monopole.</p>
  <p>Bislang agieren diese Bewegungen der Umwelt-Aktivist*innen und digitalen Menschenrechtler oft nebeneinander. Sie bieten Lösungsansätze und Ideen für ihre jeweils eigenen Themen, die inzwischen nicht nur Politik, Zivilgesellschaft, Wirtschaft, sondern sogar fast jeden Haushalt erreicht haben. Beide wollen die Welt verstehen, aber vor allem aktiv gestalten. Sie sehen, dass wesentliche Veränderungen für ein ‚gutes Leben’ sowie eine gerechte und zukunftsfähige Gesellschaft nötig sind. Doch eine demokratische und nachhaltige Gesellschaft kann nur gemeinsam gelingen – dafür müssen diese Communities zusammenkommen, voneinander lernen, die Gemeinsamkeiten ihrer Utopien erkennen und diese mit neuer Wucht umsetzen!</p>
  <p>Wie also kann Digitalisierung zur nachhaltigen Transformation der Gesellschaft und des Wirtschaftens beitragen? Wie kann Nachhaltigkeitsdenken die Techie-Szene inspirieren, sodass die Digitalisierung langfristig Bürgerrechte und individuelle Freiheiten garantiert? Wie können beispielsweise Strom aus Erneuerbaren Energien und intelligente Netze mit vereintem Wissen weiterentwickelt werden? Welche Rolle spielen die beiden Nachhaltigkeits-Säulen Ökologie und Gerechtigkeit für stabile Tech-Communities? Welche ökologischen Chancen stecken in digitalen Anwendungen etwa für Klima- und Ressourcenschutz? Welche Arten von Digitalisierung stehen diesen entgegen oder sind sogar kontraproduktiv? Wie kann die digitale Gesellschaft demokratisch und gerecht gestaltet und zugleich darauf ausgerichtet sein, die Grundlagen unseres Lebens auf diesem Planeten zu bewahren?</p>
  <p>Unter diesen Leitfragen steht „Bits & Bäume“ als eine offene Vernetzungskonferenz – für neue Perspektiven auf eine Digitalisierung mit Nachhaltigkeit! Wir wollen gegenseitigen Austausch, wir brauchen aktive Vernetzung. Dafür wollen wir</p>
  <ul>
    <li>unterschiedliche Szenen, Akteure und Organisationen in die Diskussion bringen,</li>
    <li>Schnittstellen zwischen Nachhaltigkeitsthemen und einer umsichtigen Digitalisierung herausarbeiten,</li>
    <li>visionäre Lösungen finden und mit gemeinsamer Vehemenz umsetzen.</li>
  </ul>
  <p>Neben Vorträgen wird es Raum geben für Diskussionsrunden sowie für die Planung von Projekten und Kampagnen, die die unterschiedlichen Communities verbinden: Hands-on-Workshops, Aktivisten-Infotische, Sofas oder Hackathons. „Bits & Bäume“ soll politisieren und den Auftakt geben für gemeinsame Positionen zu einer nachhaltigen Digitalisierung und wider demokratiefeindliche Trends. Zwei Konferenztage geben Anstoß für intensiven Austausch und politische Aktivitäten. Neben Akteuren aus zivilgesellschaftlichen Organisationen richten wir uns auch ausdrücklich an die interessierte Öffentlichkeit und an progressive Akteure aus Wissenschaft, Politik und Unternehmen.</p>
</article>